version: "3"
services:
  #exercise6:
  #  build: .
  #  ports:
  #    - "9005:9005"
  #  links:
  #    - mongodb
  #    - replica
  #    - messageapp
  redis:
    image: redis
    ports:
      - 6379:6379    
    volumes:
      - ./data/redis:/data/redis  
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017
  replica:
    image: mongo
    command: mongod --port 27019
    volumes:
      - ./data/replica:/data/replica
    ports:
      - 27019:27019
